### ISSUE TITLE
Bot Shows "@invalid-user" When Viewing Queue On Mobile

### ISSUE THREAD

**Issue by JoshSanch** [pattyjogal/cypher-bot#27]
Users have been reporting that they frequently see `@invalid-user` when looking at the bot queue messages on the Discord mobile client. At first, this was thought to be an issue with the client itself that we could not address.

However, I was able to correct this behavior by running a command involving Discord users, which could be a sign that the cache behavior on PC and mobile is different. We should do fetched lookups in cases where user data is not available in the cache.

**Comment by pattyjogal** [comment]
Seems to be pretty deeply tied to Discord internals; I'm going to chalk your experience up to coincidence.

https://stackoverflow.com/questions/58679839/discord-bot-normal-user-name-from-pc-but-invalid-user-from-phone
https://www.reddit.com/r/discordapp/comments/d6u21t/invaliduser_issues_on_mobile/
https://www.reddit.com/r/discordapp/comments/i8mu4m/whats_up_with_invaliduser_it_works_fine_on/

**Comment by JoshSanch** [comment]
These all mention the cache - fetched lookups do not need to use the cache in order to get user data. I'm going to reopen this and try out a fix involving fetch instead of a cache lookup.

**Comment by JoshSanch** [comment]
Relevant documentation from Discord.js: https://discord.js.org/#/docs/main/stable/class/GuildMemberManager?scrollTo=fetch

**Comment by JoshSanch** [comment]
Unfortunately, confirmed that this is an issue with the Discord mobile client that we are unable to fix. Sad :(
